### PR TITLE
OTP 27: bump `katana_code` from 2.1.0 to 2.1.1

### PR DESCRIPTION
**Pull request by paulo-ferraz-oliveira**

### CODE REVIEW

**Comment by paulo-ferraz-oliveira** [comment]
@elbrujohalcon, I can't add reviewers to this, so I'm 👋ing here.

After this, if possible, I'd request a release. Thanks.

**Review by elbrujohalcon — APPROVED** [review]

**Comment by paulo-ferraz-oliveira** [comment]
I had to push a minor update to `rebar.config` to prevent breakage on compilation. Other than that, if approved+merged, it should be good for release(GitHub)+publish(Hex.pm).

**Comment by paulo-ferraz-oliveira** [comment]
You might have to tweak the Settings for this: `build (25.2.1, 3.20.0) Expected — Waiting for status to be reported`, since I changed the target OTP version.

**Comment by elbrujohalcon** [comment]
https://hex.pm/packages/rebar3_hank/1.4.1

**Comment by paulo-ferraz-oliveira** [comment]
Perfect stuff. Thanks.

**Pull request merged**
